Remove 'org.kohsuke:pom' as parent pom
jenkinsci/archetypes pull request #646
Opened 2023-07-28 22:03 UTC by NotMyFault

This seems to be a left over and entirely unused nowadays, I was able to replay the Jenkinsfile fine locally, but pulls in [very dated](https://github.com/kohsuke/pom) dependencies, still.

2023-07-29 07:17 UTC, timja reviewed
it might be needed for publishing? cc @jglick

2023-07-29 13:40 UTC, jglick requested changes
Right, it is fine to remove the parent but you would then need to explicitly define the OSSRH-related distribution management, Nexus plugin config including auto close & release, probably some signing stuff, etc.

2023-07-29 13:42 UTC, jglick commented
Maybe it would make sense to have a child POM of `org.jenkinsci:pom`, or even a profile, that would let us use our better-maintained Maven infrastructure generally and just add in the OSSRH aspects?

2023-07-31 22:05 UTC, NotMyFault commented
> Maybe it would make sense to have a child POM of `org.jenkinsci:pom`, or even a profile, that would let us use our better-maintained Maven infrastructure generally and just add in the OSSRH aspects?

Are there that many tools we publish to the central repository? I can think of archetypes and some incrementals components only 🤔

2023-07-31 22:41 UTC, jglick commented
> I can think of archetypes and some incrementals components only

Possibly only those at this point, I do not recall.

2023-08-11 19:44 UTC, NotMyFault commented
> Right, it is fine to remove the parent but you would then need to explicitly define the OSSRH-related distribution management, Nexus plugin config including auto close & release, probably some signing stuff, etc.

Apologies for the delayed response, but I created https://github.com/NotMyFault/central-repository-pom based on the old pom with the entries we need, to sign & deploy to the central repository.
Thoughts/objections about using a custom pom with up-to-date dependencies matching our needs?

2023-08-11 20:44 UTC, jglick commented
I am not a big fan of tying this repo to something defined in a repo associated with a personal account, since if you move on we would need to pester you to accept PRs, or fork it, or something. (Yes you can add collaborators to a personal repo but with significant limitations.) Prefer either inlining what we need here (Dependabot makes it low effort to maintain) or, if we foresee other repos like `incrementals-tools` having the same requirement, introducing a POM repo in @jenkinsci (published to Central at least until such time as we set up `flatten-maven-plugin`).

2023-08-11 20:51 UTC, NotMyFault commented
> I am not a big fan of tying this repo to something defined in a repo associated with a personal account

Oh, this repo is meant to live inside the `jenkinsci` organization, but I preferred to ask if this was an acceptable approach first, before starting to host something we probably don't want to use 😅

2023-08-11 21:34 UTC, jglick commented
Oh I see! Yes from a five-second glance, https://github.com/NotMyFault/central-repository-pom/blob/c0e22ba08d1fc4ea028b46b7993da15ad0efa2c0/pom.xml seems reasonable.

2023-08-12 06:26 UTC, NotMyFault commented
> Oh I see! Yes from a five-second glance, [NotMyFault/central-repository-pom@`c0e22ba`/pom.xml](https://github.com/NotMyFault/central-repository-pom/blob/c0e22ba08d1fc4ea028b46b7993da15ad0efa2c0/pom.xml) seems reasonable.

Could you authorize [OSSRH-94106](https://issues.sonatype.org/browse/OSSRH-94106) by commenting on it, please? I didn't know we already own this namespace, and I can't mention your Jira ID for some reason.

2023-08-15 15:03 UTC, closed without merging